<?php
/**
 * @file
 * Add a field to an existing form.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Menu\MenuLinkTree;
use Drupal\Core\Menu\MenuTreeParameters;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;
use Drupal\Core\Link;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function zeesalaam_form_node_videos_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	$user = \Drupal::currentUser()->getRoles();
	if(in_array("authenticated", $user)) {
		$form['#attached']['library'][] = 'zeesalaam/video-edit';
	}
	foreach (array_keys($form['actions']) as $action) {
		if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
		  $form['actions'][$action]['#submit'][] = 'zeesalaam_video_submit';
		}
   }
   $form['field_mobile_title']['widget'][0]['value']['#title'] = "<div><div class='lblflt'>Mobile Title</div> <div id='counter'  class='counter lblflt padleft'>(Maximum Char: 74, Remaining: 0)</div></div><div class='clearfix'></div>";
  $form['field_mobile_title']['widget']['0']['value']['#attributes']['maxlength']=74;
  $form['field_mobile_title']['widget']['0']['value']['#attributes']['class'] = array("text-full","maxlen");
  
  $publishLatter = $form['field_publish_later']['widget']['#default_value'];
 
  if($publishLatter == 1 && $form['status']['widget']['value']['#default_value'] ==1) {
	  $form['field_publish_later']['#access'] = false;
	  $form['field_publish_at']['#access'] = false;
  }
  
}

function zeesalaam_form_node_videos_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	$user = \Drupal::currentUser()->getRoles();
	if(in_array("authenticated", $user)) {
		$form['#attached']['library'][] = 'zeesalaam/video-add';
        //$form['#attached']['library'][] = 'zeesalaam/video-add-css';		
	}
	foreach (array_keys($form['actions']) as $action) {
		if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
		  $form['actions'][$action]['#submit'][] = 'zeesalaam_video_submit';
		}
  }
  $form['field_mobile_title']['widget'][0]['value']['#title'] = "<div><div class='lblflt'>Mobile Title</div> <div id='counter'  class='counter lblflt padleft'>(Maximum Char: 74, Remaining: 0)</div></div><div class='clearfix'></div>";
  $form['field_mobile_title']['widget']['0']['value']['#attributes']['maxlength']=74;
  $form['field_mobile_title']['widget']['0']['value']['#attributes']['class'] = array("text-full","maxlen");
 
}
function zeesalaam_video_submit(array $form, FormStateInterface &$form_state){
	 $fid= '';
	 
     $title = $form_state->getvalue('title');
	
	 $thubnail_url = $form_state->getUserInput()['thumbimageURL'];
	 if($thubnail_url !='') {
		
		 $remoteImagePath = $thubnail_url;
		 $current_date =  date("Y/m/d");
		 $directory = 'public://'.$current_date;
		 
		 if(file_prepare_directory($directory, FILE_CREATE_DIRECTORY)) {
			$imgPath = system_retrieve_file($remoteImagePath, $directory, False, FILE_EXISTS_RENAME);
		 }else{
			$imgPath = system_retrieve_file($remoteImagePath, $directory, False, FILE_EXISTS_RENAME);
		 }
		if ($remoteImagePath) {
			$file = File::create([
				'filename' => basename($imgPath),
				'filepath' => $imgPath,
				'filemime' => \Drupal::service('file.mime_type.guesser')->guess($imgPath)  ,
				'filesize' => filesize($imgPath),
				'uid' => 18,
				'timestamp' => time(),
				'uri' => $imgPath,
				'status' => FILE_STATUS_PERMANENT,
			]);
			$file->save();
			$fid = $file->id();
		}
        if($fid) {
			$entity = $form_state->getFormObject()->getEntity();
			$entity->set("field_image", [
			'target_id' => $fid,
			'alt' => $title[0]['value'],
			'title' => $title[0]['value']
			]);
			$publishedLatter = $form_state->getvalue('field_publish_later');
			$publishedLatterVal = $publishedLatter[0]['value'];	
			if($publishedLatterVal == 0) {
				$entity->setUnpublished(TRUE);
			} else {
				$entity->setPublished(TRUE);
			}
			$entity->save();
		} else {
			$nidd[] = $form_state->getvalue('nid');
			entity_delete_multiple('node', $nidd);
			$errors = drupal_get_messages('status');
			unset($_SESSION['_symfony_flashes']['status']);
			drupal_set_message(t('Some Error occur when image uploading ! Please try again'),'error');
			$response = new RedirectResponse("/zee-salaam/admin/content");
			$response->send();
			return;
		}		
		

	} else {
		$nidd[] = $form_state->getvalue('nid');
		entity_delete_multiple('node', $nidd);
		$errors = drupal_get_messages('status');
		unset($_SESSION['_symfony_flashes']['status']);
		drupal_set_message(t('Some Error occur when image uploading ! Please try again'),'error');
		$response = new RedirectResponse("/zee-salaam/admin/content");
        $response->send();
        return;
	}
	
    
}
function zeesalaam_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
	switch ($entity->bundle()) {
	
		case 'videos':
      
		$body_field = $entity->get('body');
        $field_value = $body_field->getValue();
		$bodyValue = strip_tags($field_value[0]['value']);
		$summaryValue = $field_value[0]['summary'];
		$format = $field_value[0]['format'];
		
		if(trim($entity->get('field_home_title')->value) == '') {
			$entity->field_home_title->value = $entity->get('title')->value;
		}
		
		
		if (empty(trim($summaryValue)) && !empty(trim($bodyValue))) {

			$mybody=strip_tags($field_value[0]['value']);
			 $pos=stripos($mybody,"\n");
			
			
			$mybody= substr($bodyValue,0,$pos);
			
			
			$pos =stripos($mybody,":");
			
		
			if($pos>0)
			{
			$entity->body->summary = ltrim(strip_tags(substr($mybody,$pos+1)),'&nbsp;');
			}
			
		} 
		
		break;
	}
}
function zeesalaam_user_login(\Drupal\user\UserInterface $account) {
    $response = new RedirectResponse("/salaam/admin/content");
    $response->send();
    return;
}
?>
